# Swagger/OpenAPI settings
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.show-actuator=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_lab4_notifications
spring.datasource.username=postgres
spring.datasource.password=1909
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL Initialization (??? ?????????????? ???????? data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.example=DEBUG

# JWT Configuration
jwt.secret=verySecretKeyForJwtTokenVerySecretKey12345
jwt.expiration=3600000